["bag"] = {
    ["name"] = "bag",
    ["label"] = "Bag",
    ["weight"] = 5,
    ["type"] = "item",
    ["image"] = "bag.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = ""
},
["hack_usb"] = {
    ["name"] = "hack_usb",
    ["label"] = "Hack USB",
    ["weight"] = 5,
    ["type"] = "item",
    ["image"] = "hack_usb.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = ""
},
["crowbar"] = {
    ["name"] = "crowbar",
    ["label"] = "Crowbar",
    ["weight"] = 5,
    ["type"] = "item",
    ["image"] = "crowbar.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = ""
},
["cutter"] = {
    ["name"] = "cutter",
    ["label"] = "Cutter",
    ["weight"] = 5,
    ["type"] = "item",
    ["image"] = "cutter.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = ""
},
["gold_uzi"] = {
    ["name"] = "gold_uzi",
    ["label"] = "Gold Uzi",
    ["weight"] = 200,
    ["type"] = "item",
    ["image"] = "gold_uzi.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = ""
},
["ammo_smg"] = {
    ["name"] = "ammo_smg",
    ["label"] = "SMG Ammo",
    ["weight"] = 200,
    ["type"] = "item",
    ["image"] = "ammo_smg.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = ""
},
["ammo_pistol"] = {
    ["name"] = "ammo_pistol",
    ["label"] = "Pistol Ammo",
    ["weight"] = 200,
    ["type"] = "item",
    ["image"] = "blowtorch.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = "0x0x"
},
["ammo_rifle"] = {
    ["name"] = "ammo_rifle",
    ["label"] = "Rifle Ammo",
    ["weight"] = 200,
    ["type"] = "item",
    ["image"] = "ammo_rifle.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = ""
},
["pistol_suppressor"] = {
    ["name"] = "pistol_suppressor",
    ["label"] = "Pistol Suppressor",
    ["weight"] = 100,
    ["type"] = "item",
    ["image"] = "pistol_suppressor.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = true,
    ["combinable"] = nil,
    ["description"] = ""
}
["rifle_suppressor"] = {
    ["name"] = "rifle_suppressor",
    ["label"] = "Rifle Suppressor",
    ["weight"] = 100,
    ["type"] = "item",
    ["image"] = "rifle_suppressor.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = true,
    ["combinable"] = nil,
    ["description"] = ""
}
["smg_suppressor"] = {
    ["name"] = "smg_suppressor",
    ["label"] = "SMG Suppressor",
    ["weight"] = 100,
    ["type"] = "item",
    ["image"] = "smg_suppressor.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = true,
    ["combinable"] = nil,
    ["description"] = ""
}
["pistol_clip"] = {
    ["name"] = "smg_suppressor",
    ["label"] = "Pistol Clip",
    ["weight"] = 100,
    ["type"] = "item",
    ["image"] = "smg_suppressor.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = true,
    ["combinable"] = nil,
    ["description"] = ""
}
["smg_clip"] = {
    ["name"] = "smg_clip",
    ["label"] = "SMG Clip",
    ["weight"] = 100,
    ["type"] = "item",
    ["image"] = "smg_clip.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = true,
    ["combinable"] = nil,
    ["description"] = ""
}
["rifle_clip"] = {
    ["name"] = "rifle_clip",
    ["label"] = "Rifle Clip",
    ["weight"] = 100,
    ["type"] = "item",
    ["image"] = "rifle_clip.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = true,
    ["combinable"] = nil,
    ["description"] = ""
}

